# -*- coding: utf-8 -*-
"""03-Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/LangChain-OpenTutorial/LangChain-OpenTutorial/blob/main/15-Agent/03-Agent.ipynb

# Tool Calling Agent

- Author: [Kenny Jung](https://www.linkedin.com/in/kwang-yong-jung)
- Peer Review:
- Proofread : [Chaeyoon Kim](https://github.com/chaeyoonyunakim)
- This is a part of [LangChain Open Tutorial](https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial)

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/LangChain-OpenTutorial/LangChain-OpenTutorial/blob/main/15-Agent/03-Agent.ipynb)[![Open in GitHub](https://img.shields.io/badge/Open%20in%20GitHub-181717?style=flat-square&logo=github&logoColor=white)](https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/blob/main/15-Agent/03-Agent.ipynb)

## Overview

This tutorial explains tool calling in LangChain, allowing models to detect when one or more **tools** are **called and what inputs to pass** to those tools.

When making API calls, you can define tools and intelligently guide the model to generate structured objects, such as JSON, containing arguments for calling these tools.

The goal of the tools API is to provide more reliable generation of valid and useful **tool calls** beyond what standard text completion or chat APIs can achieve.

You can create agents that iteratively call tools and receive results until a query is resolved by integrating this structured output with the ability to bind multiple tools to a tool-calling chat model and letting the model choose which tools to call.

This represents a more **generalized version** of the OpenAI tools agent which was specifically designed for OpenAI's particular tool-calling style.

This agent uses LangChain's ToolCall interface to support a broader spectrum of provider implementations beyond OpenAI, including ```Anthropic```, ```Google Gemini```, and ```Mistral```.


### Table of Contents

- [Overview](#overview)
- [Environment Setup](#environment-setup)
- [Creating Tools](#creating-tools)
- [Constructing an Agent Prompt](#constructing-an-agent-prompt)
- [Creating Agent](#creating-agent)
- [AgentExecutor](#agentexecutor)
- [Checking step-by-step results using Stream output](#checking-step-by-step-results-using-stream-output)
- [Customizing intermediate step output using user-defined functions](#customizing-intermediate-step-output-using-user-defined-functions)
- [Communicating Agent with previous conversation history](#communicating-agent-with-previous-conversation-history)

### References

- [LangChain Python API Reference > langchain: 0.3.14 > agents > create_tool_calling_agent](https://python.langchain.com/api_reference/langchain/agents/langchain.agents.tool_calling_agent.base.create_tool_calling_agent.html#create-tool-calling-agent)
- [LangChain Python API Reference > langchain: 0.3.14 > core > runnables > langchain_core.runnables.history > RunnableWithMessageHistory](https://python.langchain.com/api_reference/core/runnables/langchain_core.runnables.history.RunnableWithMessageHistory.html)

![](https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/blob/main/15-Agent/assets/15-agent-agent-concept.png?raw=1)

----

## Environment Setup

Set up the environment. You may refer to [Environment Setup](https://wikidocs.net/257836) for more details.

**[Note]**
- ```langchain-opentutorial``` is a package that provides a set of easy-to-use environment setup, useful functions and utilities for tutorials.
- You can checkout the [```langchain-opentutorial```](https://github.com/LangChain-OpenTutorial/langchain-opentutorial-pypi) for more details.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture --no-stderr
# %pip install langchain-opentutorial

# Install required packages
from langchain_opentutorial import package

package.install(
    [
        "langsmith",
        "langchain",
        "langchain_core",
        "langchain_openai",
        "langchain_community",
    ],
    verbose=False,
    upgrade=False,
)

# Set environment variables
from langchain_opentutorial import set_env

set_env(
    {
        "OPENAI_API_KEY": "",
        "LANGCHAIN_API_KEY": "",
        "LANGCHAIN_TRACING_V2": "true",
        "LANGCHAIN_ENDPOINT": "https://api.smith.langchain.com",
        "LANGCHAIN_PROJECT": "ToolCallingAgent",
    }
)

"""You can alternatively set ```OPENAI_API_KEY``` in ```.env``` file and load it.

[Note] This is not necessary if you've already set ```OPENAI_API_KEY``` in previous steps.
"""

from dotenv import load_dotenv

load_dotenv(override=True)

"""## Creating Tools

LangChain allows you to define custom tools that your agents can interact with. You can create tools for searching news or executing Python code.

The ```@tool``` decorator is used to create tools:
- ```TavilySearchResults``` is a tool for searching news.
- ```PythonREPL``` is a tool for executing Python code.

"""

from langchain.tools import tool
from typing import List, Dict, Annotated
from langchain_community.tools import TavilySearchResults
from langchain_experimental.utilities import PythonREPL


# Creating tool for searching news
@tool
def search_news(query: str) -> List[Dict[str, str]]:
    """Search news by input keyword using Tavily Search API"""
    news_tool = TavilySearchResults(
        max_results=3,
        include_answer=True,
        include_raw_content=True,
        include_images=True,
        # search_depth="advanced",
        # include_domains = [],
        # exclude_domains = []
    )
    return news_tool.invoke(query, k=3)


# Creating tool for executing python code
@tool
def python_repl_tool(
    code: Annotated[str, "The python code to execute to generate your chart."],
):
    """Use this tool to execute Python code. If you want to see the output of a value,
    you should print it using print(...). This output is visible to the user."""
    result = ""
    try:
        result = PythonREPL().run(code)
    except BaseException as e:
        print(f"Failed to execute. Error: {repr(e)}")
    finally:
        return result


print(f"Tool name: {search_news.name}")
print(f"Tool description: {search_news.description}")
print(f"Tool name: {python_repl_tool.name}")
print(f"Tool description: {python_repl_tool.description}")

# Creating tools
tools = [search_news, python_repl_tool]

"""## Constructing an Agent Prompt

- ```chat_history```: This variable stores the conversation history if your agent supports multi-turn. (Otherwise, you can omit this.)
- ```agent_scratchpad```: This variable serves as temporary storage for intermediate variables.
- ```input```: This variable represents the user's input.
"""

from langchain_core.prompts import ChatPromptTemplate

# Creating prompt
# Prompt is a text that describes the task the model should perform. (input the name and role of the tool)
prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are a helpful assistant. "
            "Make sure to use the `search_news` tool for searching keyword related news.",
        ),
        ("placeholder", "{chat_history}"),
        ("human", "{input}"),
        ("placeholder", "{agent_scratchpad}"),
    ]
)

"""## Creating Agent

Define an agent using the ```create_tool_calling_agent``` function.
"""

from langchain_openai import ChatOpenAI
from langchain.agents import create_tool_calling_agent

# Creating LLM
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

# Creating Agent
agent = create_tool_calling_agent(llm, tools, prompt)

"""## ```AgentExecutor```

The ```AgentExecutor``` is a class for managing an agent that uses tools.

**Key properties**
- ```agent```: the underlying agent responsible for creating plans and determining actions at each step of the execution loop.
- ```tools```: a list containing all the valid tools that the agent is authorized to use.
- ```return_intermediate_steps```: boolean flag determins whether to return the intermediate steps the agent took along with the final output.
- ```max_iterations```: a maximum number of steps the agent can take before the execution loop is terminated.
- ```max_execution_time```: the maximum amount of time the execution loop is allowed to run.
- ```early_stopping_method```: a defined method how to handle situations when the agent does not return an ```AgentFinish```. ("force" or "generate")
  - ```"force"``` : returns a string indicating that the execution loop was stopped due to reaching the time or iteration limit.
  - ```"generate"``` : calls the agent's LLM chain once to generate a final answer based on the previous steps taken.
- ```handle_parsing_errors``` : a specification how to handle parsing errors. (You can set ```True```, ```False```, or provide a custom error handling function.)
- ```trim_intermediate_steps``` : method of trimming intermediate steps. (You can set ```-1``` to keep all steps, or provide a custom trimming function.)

**Key methods**
1. ```invoke``` : Executes the agent.
2. ```stream``` : Stream the steps required to reach the final output.

**Key features**
1. **Tool validation** : Ensure that the tool is compatible with the agent.
2. **Execution control** : Set maximum interations and execution time limits to manage agent bahavior.
3. **Error handling** : Offers various processing options for output parsing errors.
4. **Intermediate step management** : Allows for trimming intermediate steps or returning options for debugging.
5. **Asynchronous support** : Supports asynchronous execution and streaming of results.

**Optimization tips**
- Set appropriate values for ```max_iterations``` and ```max_execution_time``` to manage execution time.
- Use ```trim_intermediate_steps``` to optimize memory usage.
- For complex tasks, use the ```stream``` method to monitor step-by-step results.
"""

from langchain.agents import AgentExecutor

# Create AgentExecutor
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    max_iterations=10,
    max_execution_time=10,
    handle_parsing_errors=True,
)

# Run AgentExecutor
result = agent_executor.invoke({"input": "Search news about AI Agent in 2025."})

print("Agent execution result:")
print(result["output"])

"""## Checking step-by-step results using Stream output

We will use the ```stream()``` method of ```AgentExecutor``` to stream the intermediate steps of the agent.

The output of ```stream()``` alternates between (Action, Observation) pairs, and finally ends with the agent's answer if the goal is achieved.

The flow will look like the followings:

1. Action output
2. Observation output
3. Action output
4. Observation output

... (Continue until the goal is achieved) ...

Then, the agent will conclude a final answer if its goal is achieved.

The following table summarizes the content you'll encounter in the output:

| Output | Description |
|--------|-------------|
| Action | ```actions```: Represents the ```AgentAction``` or its subclass. <br>```messages```: Chat messages corresponding to the action call. |
| Observation | ```steps```: A record of the agent's work, including the current action and its observation. <br>```messages```: Chat messages containing the results from function calls (i.e., observations). |
| Final Answer | ```output```: Represents ```AgentFinish``` signal. <br>```messages```: Chat messages containing the final output. |
```
"""

from langchain.agents import AgentExecutor

# Create AgentExecutor
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=False,
    handle_parsing_errors=True,
)

# Run in streaming mode
result = agent_executor.stream({"input": "Search news about AI Agent in 2025."})

for step in result:
    # Print intermediate steps
    print(step)
    print("===" * 20)

"""## Customizing intermediate step output using user-defined functions

You can define the following 3 functions to customize the intermediate steps output:

- ```tool_callback```: This function handles the output generated by tool calls.
- ```observation_callback```: This function deals with the observation data output.
- ```result_callback```: This function allows you to handle the final answer output.

Here's an example callback function that demonstrates how to clean up the intermediate steps of the Agent.

This callback function can be useful when presenting intermediate steps to users in an application like Streamlit.
"""

from typing import Dict, Any


# Create AgentStreamParser class
class AgentStreamParser:
    def __init__(self):
        pass

    def tool_callback(self, tool: Dict[str, Any]) -> None:
        print("\n=== Tool Called ===")
        print(f"Tool: {tool.get('tool')}")
        print(f"Input: {tool.get('tool_input')}")
        print("==================\n")

    def observation_callback(self, step: Dict[str, Any]) -> None:
        print("\n=== Observation ===")
        observation_data = step["steps"][0].observation
        print(f"Observation: {observation_data}")
        print("===================\n")

    def result_callback(self, result: str) -> None:
        print("\n=== Final Answer ===")
        print(result)
        print("====================\n")

    def process_agent_steps(self, step: Dict[str, Any]) -> None:
        if "actions" in step:
            for action in step["actions"]:
                self.tool_callback(
                    {"tool": action.tool, "tool_input": action.tool_input}
                )
        elif "output" in step:
            self.result_callback(step["output"])
        else:
            self.observation_callback(step)


# Create AgentStreamParser instance
agent_stream_parser = AgentStreamParser()

"""Check the response process of your Agent in streaming mode."""

# Run in streaming mode
result = agent_executor.stream({"input": "Generate a pie chart using matplotlib."})
# result = agent_executor.stream({"input": "Search news about AI Agent in 2025."})


for step in result:
    agent_stream_parser.process_agent_steps(step)

# Run in streaming mode
result = agent_executor.stream({"input": "Search news about AI Agent in 2025."})


for step in result:
    agent_stream_parser.process_agent_steps(step)

"""Modify the callback function to use it."""

from typing import Dict, Any, Callable


# 1. Define AgentCallbacks class
class AgentCallbacks:
    def __init__(
        self,
        tool_callback: Callable,
        observation_callback: Callable,
        result_callback: Callable,
    ):
        self.tool_callback = tool_callback
        self.observation_callback = observation_callback
        self.result_callback = result_callback


# 2. Define AgentStreamParser class
class AgentStreamParser:
    def __init__(self, callbacks: AgentCallbacks):
        self.callbacks = callbacks

    def process_agent_steps(self, step: Dict[str, Any]) -> None:
        if "actions" in step:
            for action in step["actions"]:
                self.callbacks.tool_callback(
                    {"tool": action.tool, "tool_input": action.tool_input}
                )
        elif "output" in step:
            self.callbacks.result_callback(step["output"])
        else:
            self.callbacks.observation_callback(step)


# 3. Define callback functions
def tool_callback(tool) -> None:
    print("<<<<<<< Tool Called >>>>>>")
    print(f"Tool: {tool.get('tool')}")
    print(f"Input: {tool.get('tool_input')}")
    print("<<<<<<< Tool Called >>>>>>")


def observation_callback(step) -> None:
    print("<<<<<<< Observation >>>>>>")
    observation_data = step["steps"][0].observation
    print(f"Observation: {observation_data}")
    print("<<<<<<< Observation >>>>>>")


def result_callback(result: str) -> None:
    print("<<<<<<< Final Answer >>>>>>")
    print(result)
    print("<<<<<<< Final Answer >>>>>>")


# 4. Example usage
# Wrap callback functions into AgentCallbacks instance
agent_callbacks = AgentCallbacks(
    tool_callback=tool_callback,
    observation_callback=observation_callback,
    result_callback=result_callback,
)

# Create AgentStreamParser instance
agent_stream_parser = AgentStreamParser(agent_callbacks)

"""Check the output content. You can reflect the output value of your callback functions, providing intermediate content that has been changed."""

# Request streaming output for the query
result = agent_executor.stream({"input": "Search news about AI Agent in 2025."})

for step in result:
    # Output intermediate steps using parser
    agent_stream_parser.process_agent_steps(step)

"""## Communicating Agent with previous conversation history

To remember past conversations, you can wrap the ```AgentExecutor``` with ```RunnableWithMessageHistory```.

For more details on ```RunnableWithMessageHistory```, please refer to the link below.

**Reference**
- [LangChain Python API Reference > langchain: 0.3.14 > core > runnables > langchain_core.runnables.history > RunnableWithMessageHistory](https://python.langchain.com/api_reference/core/runnables/langchain_core.runnables.history.RunnableWithMessageHistory.html)
"""

from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory

# Create a dictionary to store session_id
store = {}


# Function to get session history based on session_id
def get_session_history(session_ids):
    if session_ids not in store:  # If session_id is not in store
        # Create a new ChatMessageHistory object and store it in store
        store[session_ids] = ChatMessageHistory()
    return store[session_ids]  # Return session history for the corresponding session_id


# Create an agent with chat message history
agent_with_chat_history = RunnableWithMessageHistory(
    agent_executor,
    # Chat session_id
    get_session_history,
    # The key for the question input in the prompt: "input"
    input_messages_key="input",
    # The key for the message input in the prompt: "chat_history"
    history_messages_key="chat_history",
)

# Request streaming output for the query
response = agent_with_chat_history.stream(
    {"input": "Hello! My name is Teddy!"},
    # Set session_id
    config={"configurable": {"session_id": "abc123"}},
)

# Check the output
for step in response:
    agent_stream_parser.process_agent_steps(step)

# Request streaming output for the query
response = agent_with_chat_history.stream(
    {"input": "What is my name?"},
    # Set session_id
    config={"configurable": {"session_id": "abc123"}},
)

# Check the output
for step in response:
    agent_stream_parser.process_agent_steps(step)

# Request streaming output for the query
response = agent_with_chat_history.stream(
    {
        "input": "My email address is teddy@teddynote.com. The company name is TeddyNote Co., Ltd."
    },
    # Set session_id
    config={"configurable": {"session_id": "abc123"}},
)

# Check the output
for step in response:
    agent_stream_parser.process_agent_steps(step)

# Request streaming output for the query
response = agent_with_chat_history.stream(
    {
        "input": "Search the latest news and write it as the body of the email. "
        "The recipient is `Ms. Sally` and the sender is my personal information."
        "Write in a polite tone, and include appropriate greetings and closings at the beginning and end of the email."
    },
    # Set session_id
    config={"configurable": {"session_id": "abc123"}},
)

# Check the output
for step in response:
    agent_stream_parser.process_agent_steps(step)

# Request streaming output for the query
response = agent_with_chat_history.stream(
    {"input": "What is my name?"},
    # Set session_id
    config={"configurable": {"session_id": "def456"}},
)

# Check the output
for step in response:
    agent_stream_parser.process_agent_steps(step)